services:
  # ---------------------------------------------------------
  # MARS SIMULATOR (provided by the instructor)
  # ---------------------------------------------------------
  simulator:
    image: mars-iot-simulator:multiarch_v1
    container_name: mars_simulator
    ports:
      - "8080:8080"
    networks:
      - aresguard_net
    restart: always

  # ---------------------------------------------------------
  # MESSAGE BROKER (RabbitMQ)
  # ---------------------------------------------------------
  broker:
    image: rabbitmq:3-management
    container_name: aresguard_broker
    ports:
      - "5672:5672" # Port for AMQP communication (Ingestion -> Broker -> Services)
      - "15672:15672" # Port for the Management Web UI
    environment:
      RABBITMQ_DEFAULT_USER: ares
      RABBITMQ_DEFAULT_PASS: mars2036
    networks:
      - aresguard_net
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "-q", "ping"]
      interval: 15s
      timeout: 10s
      retries: 10

  # ---------------------------------------------------------
  # DATABASE (PostgreSQL)
  # ---------------------------------------------------------
  database:
    image: postgres:15-alpine
    container_name: aresguard_db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: ares
      POSTGRES_PASSWORD: mars2036
      POSTGRES_DB: aresguard
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - aresguard_net
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ares -d aresguard"]
      interval: 10s
      timeout: 5s
      retries: 5
  # ---------------------------------------------------------
  # CUSTOM MICROSERVICES
  # ---------------------------------------------------------
  ingestion:
     build: ./ingestion
     container_name: aresguard_ingestion
     depends_on:
       broker:
         condition: service_healthy
       simulator:
         condition: service_started
     networks:
       - aresguard_net
     environment:
       - SIMULATOR_URL=http://mars_simulator:8080/api/sensors
       - BROKER_HOST=aresguard_broker
       - RABBITMQ_DEFAULT_USER=ares
       - RABBITMQ_DEFAULT_PASS=mars2036

  rule_engine:
    build: ./rule_engine
    container_name: aresguard_rule_engine
    environment:
      - PYTHONUNBUFFERED=1
      - BROKER_HOST=aresguard_broker
      - RABBITMQ_DEFAULT_USER=ares
      - RABBITMQ_DEFAULT_PASS=mars2036
      - DATABASE_URL=host=aresguard_db dbname=aresguard user=ares password=mars2036
      - SIMULATOR_URL=http://mars_simulator:8080/api/actuators
    depends_on:
      broker:      
        condition: service_healthy
      database:          
        condition: service_healthy
    networks:
      - aresguard_net 
    ports:
      - "8001:8000"
  api_gateway:
      build: ./api_gateway
      container_name: aresguard_api_gateway
      ports:
        - "8000:8000"
      depends_on:
        broker:
          condition: service_healthy
        database:
          condition: service_healthy
      networks:
        - aresguard_net
      environment:
        - PYTHONUNBUFFERED=1
        - BROKER_HOST=aresguard_broker
        - RABBITMQ_DEFAULT_USER=ares
        - RABBITMQ_DEFAULT_PASS=mars2036
        - SIMULATOR_URL=http://mars_simulator:8080/api/actuators

  frontend:
    build: ./frontend
    container_name: aresguard_frontend
    ports:
      - "3000:80"
    depends_on:
      - api_gateway
    networks:
      - aresguard_net

networks:
  aresguard_net:
    driver: bridge

volumes:
  pgdata: # Volume to persist DB data (Rules and Logs)